name: "Fuzz: jamzilla"

on:
  workflow_dispatch:
  push:
    branches: [graymatter-fuzz-source]  # temporary: remove before merge

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jamzilla
      docker_image: 'ghcr.io/ascrivener/jamzilla-tiny:edge'
      docker_cmd: '-socket {TARGET_SOCK}'
      docker_env: 'PVM_MODE=jit'
